### ISSUE TITLE
不支持县级地图

### ISSUE THREAD

**Issue by xuefengliang** [Lchiffon/REmap#10]
目前只能支持市级地图，县级地图无法支持。我有mapinfo格式的全国的县级地图，可提供使用，能否在remap中支持想一下？

**Comment by xuefengliang** [comment]
https://www.dropbox.com/s/aev4ubwyr140bod/%E5%85%A8%E5%9B%BD%E5%8E%BF%E7%BA%A7.rar?dl=0,国内县级地图

**Comment by Lchiffon** [comment]
这个版本的数据格式和Echarts2地图使用的方式有些不同,可能短期内不会考虑支持

有计划明年写一个专门支持geojson的数据包来处理这个问题

**Comment by Lchiffon** [comment]
[leafletCN](http://github.com/lchiffon/leafletCN) 已支持 例子见http://langdawei.com/2017/01/07/aqi.html

**Comment by xuefliang** [comment]
leafletCN如何做县级迁徙地图？
