### ISSUE TITLE
关于remapc的问题，data替换成自己的数据后执行不显示地图，只出代码的问题。

### ISSUE THREAD

**Issue by coreanachina** [Lchiffon/REmap#12]
源码是：
p = remapC(data,maptype = "china",color = 'skyblue')
knitrREmap(p)
执行后不显示地图，只有一堆代码：
<div id="ID_20161205140052_938968" style="height:300px; width:100%"></div>
<script>  var myChart = echarts.init(document.getElementById("ID_20161205140052_938968"));

                       var optionID_20161205140052_938968 = {
  backgroundColor: '#D9D9D9',
  color: ['gold','aqua','lime'],
  title : {
    text: '',
    subtext:'',
    x:'center',
    textStyle : {
      color: '#1b1b1b'
    }
  },
  tooltip : {
    trigger: 'item',
    formatter: function (v) {
			if(typeof(v[2])=='number'){
			return(v[1]+': '+v[2])
			}else if(v[2].tooltipValue!=null){
          	return v[2].tooltipValue;
          }else{
            return v[1];
          }
  }},
    legend: {
        show:false,
        orient: 'vertical',
        x:'left',
        data:['Data'],
      	textStyle:{color:'#D9D9D9'}

    },
  toolbox: {
    show : true,
    orient : 'vertical',
    x: 'right',
    y: 'center',
    feature : {
      mark : {show: true},
      dataView : {show: true, readOnly: false},
      restore : {show: true},
      saveAsImage : {show: true}
    }
  },
  dataRange: {
    min : -5122,
    max : 81949,
    calculable : true,
    color: ['skyblue', 'white'],
    textStyle:{
      color:'#1b1b1b'
    }
  },
  series : [
    {
    name:'Data',
    type:'map',
    mapType: 'china',
    itemStyle:{
    normal:{
    borderColor:'rgba(100,149,237,1)',
    borderWidth: 0.5,
    label:{show:true,textStyle:{color:'#1b1b1b'}},
    },
    emphasis:{label:{show:true,textStyle:{color:'#1b1b1b'}}}
  },
  data:[{name:'安徽',value:  140},
		{name:'澳门',value:    0},
		{name:'北京',value:10433},
		{name:'福建',value: 4078},
		{name:'甘肃',value:   55},
		{name:'广东',value: 2426},
		{name:'广西',value: 1268},
		{name:'贵州',value:   72},
		{name:'海南',value: 5823},
		{name:'河北',value: 1929},
		{name:'河南',value:    0},
		{name:'黑龙江',value:    0},
		{name:'湖北',value:  188},
		{name:'湖南',value:   24},
		{name:'吉林',value:    6},
		{name:'江苏',value: 1869},
		{name:'江西',value:   20},
		{name:'辽宁',value: 2685},
		{name:'内蒙古',value:    0},
		{name:'宁夏',value:  183},
		{name:'青海',value:    0},
		{name:'山东',value:76827},
		{name:'山西',value:   30},
		{name:'陕西',value:  436},
		{name:'上海',value: 3251},
		{name:'四川',value:  264},
		{name:'台湾',value:    0},
		{name:'天津',value: 4629},
		{name:'西藏',value:    0},
		{name:'香港',value:    0},
		{name:'新疆',value:  102},
		{name:'云南',value:  972},
		{name:'浙江',value: 5354},
		{name:'重庆',value:   34}]
  
  
  }]
};
  myChart.setOption(optionID_20161205140052_938968);	</script>

请问各位大神，这种情况怎么解决？
data的数据如附件图示：
![default](https://cloud.githubusercontent.com/assets/18343984/20875090/edb52da8-baf2-11e6-8d37-976ddeecfff2.JPG)

**Comment by Lchiffon** [comment]
如果你不用knitr,直接在console打p或者plot(p)就可以了

**Comment by coreanachina** [comment]
谢谢，问题已经解决。
