### ISSUE TITLE
remapC输出的地图不显示value值，请教各位大神可能的原因是什么？

### ISSUE THREAD

**Issue by coreanachina** [Lchiffon/REmap#13]
源码：
psd = remapC(aggsd,maptype = "shandong",color = 'skyblue')
plot(psd)
问题：输出之后地图上不显示value的值。如下图所示：
![1](https://cloud.githubusercontent.com/assets/18343984/20878603/dd899492-bb0a-11e6-87ab-660a52caaaf2.jpg)

aggsd是数据框，如下图所示：
![default](https://cloud.githubusercontent.com/assets/18343984/20878528/6cb69904-bb0a-11e6-87b1-2da97cd9e4ca.JPG)

**Comment by Lchiffon** [comment]
用`mapNames`获取标准的城市名,看起来你要在后面加一个'市'字

```
mapNames("山东")
 [1] "烟台市" "临沂市" "潍坊市" "青岛市" "菏泽市" "济宁市"
 [7] "德州市" "滨州市" "聊城市" "东营市" "济南市" "泰安市"
[13] "威海市" "日照市" "淄博市" "枣庄市" "莱芜市"
```

**Comment by coreanachina** [comment]
谢谢，试过了，是因为缺少了一个市字。
