### ISSUE TITLE
使用remapB方法生成的网页一直报错

### ISSUE THREAD

**Issue by alg-jmx** [Lchiffon/REmap#14]
<!DOCTYPE html><html><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><script type="text/javascript">// If user visit a illegal link "http://echarts.baidu.com/asdf/zxcv.html",
// 404.html will show but folder level is incorrect.
// I have no time to figure that out, so use this stupid approach.
location.href = 'http://echarts.baidu.com/404.html'</script></head></html>

这个错误信息主要是生成的网页中
` <div id='main'></div>
                <script src='http://echarts.baidu.com/build/dist/echarts.js'></script>
                <script type='text/javascript' src='http://api.map.baidu.com/api?v=2.0&ak=q9U1lWgCK1aBGVC1DVWrgWa7'></script>
                <script src='http://echarts.baidu.com/doc/asset/js/jquery.min.js'></script>
                <script>

                (function () {
                require.config({
                paths: {
                echarts:'http://echarts.baidu.com/doc/example/www/js'
                },
                packages: [
                {
                name: 'BMap',
                location: 'http://echarts.baidu.com/extension/BMap/src',
                main: 'main'
                }
                ]
                });`
location 地址无法访问

**Comment by Lchiffon** [comment]
贴下代码

**Comment by alg-jmx** [comment]
`remapB(get_city_coord('中国'), markPointData = twoTemp, geoData = position,
             title = 'heat map',subtitle = '足迹', 
             markPointTheme = markPointControl(symbol = 'pin',
                                               symbolSize = 5,
                                               effect = F))`

**Comment by alg-jmx** [comment]
而且生成的网页中，中文地址都是乱码
{name:'ÓÜÑôÇøÐ¡¼Íº¹¾®¿ËÁº´åÉÂÎ÷»ªµçÓÜºáÃºµçÓÐÏÞÔðÈÎ¹«Ë¾3ºÅÂ¥504',value:{colorValue:'5'},symbol:'pin'},
{name:'ºáÉ½ÏØ¶þ½Ö½ñÔ·Ð¡ÇøÒ»ºÅÂ¥Ò»µ¥Ôª201',value:{colorValue:'6'},symbol:'pin'},
{name:'¶¨±ßÏØ³¤³Ç±±½ÖãåÑôÊ±ÉÐ¶«100Ã×',value:{colorValue:'8'},symbol:'pin'},
{name:'ÓÜÑôÇøº½ÓîÂ·½ÖµÀÎ÷É³°²ÖÃÐ¡Çø6ºÅÂ¥3µ¥Ôª401',value:{colorValue:'5'},symbol:'pin'},
{name:'¾¸±ßÏØÎ÷ÐÂ½Ö¾¸±ßÏØÎ÷ÐÂ½ÖöÎÔ´Ð¡Çø4µ¥Ôª2072',value:{colorValue:'7'},symbol:'pin'},
{name:'ÓÜÑôÇøÎÄ»¯Â·³ÐÆ½Ïï6ÅÅ2ºÅ',value:{colorValue:'5'},symbol:'pin'},
{name:'ËçµÂÏØÎÄ»¯Â·²©ÔÃ¸®1ºÅÂ¥4µ¥Ôª401ÊÒ',value:{colorValue:'4'},symbol:'pin'},
{name:'ÓÜÑôÇø¹ÄÂ¥½ÖµÀ°ìÊÂ´¦ÂíµêÏï14ºÅ',value:{colorValue:'5'},symbol:'pin'},
{name:'ÓÜÑôÇø½¨ÓÜÂ·ÕýÔ´Ð¡Çø3µ¥Ôª1003ÊÒ',value:{colorValue:'5'},symbol:'pin'},
{name:'¶¨±ßÏØ¶¨±ßÕòÌì¼ÑÐ¡Çø2ºÅÂ¥3µ¥Ôª302ÊÒ',value:{colorValue:'8'},symbol:'pin'},
{name:'¶¨±ßÏØÏ×ÖÒÂ·ÐËÔ´ÄÏÇø26ºÅÂ¥Ò»µ¥Ôª602',value:{colorValue:'8'},symbol:'pin'},
{name:'ÉñÄ¾ÏØ´óÁøËþÕò´óÁøËþÕòÁ¸¸»Â·2ºÅ',value:{colorValue:'3'},symbol:'pin'},
{name:'ÉñÄ¾ÏØ½õ½çÕò³¤³ÇÂ·001ºÅ
ÉñÄ¾ÏØ½õ½çµÚÒ»Ð¡Ñ§¹«Ô¢Â¥306ÊÒ',value:{colorValue:'3'},symbol:'pin'},
{name:'ÓÜÑôÇø½ðÑôÐ¡ÇøÑôÑôÒøÉ³Ô·29ºÅÂ¥1µ¥Ôª201ÊÒ',value:{colorValue:'5'},symbol:'pin'},
{name:'ÓÜÑôÇøÍÕ·åÂ·ÓÜÁÖÊÐÓÜÑôÇø¶«É³Ö¾¿Æ³ÇÐ¡Çø7ºÅÂ¥2µ¥Ôª402',value:{colorValue:'5'},symbol:'pin'},

**Comment by Lchiffon** [comment]
确认下你传入的字符是不是UTF-8的字符，

**Comment by alg-jmx** [comment]
在调用remapB方法之前的中文显示都是正常，也是utf-8编码，调用后生成的网页中就是那个乱码状态

**Comment by Lchiffon** [comment]
试试Sys.setlocale("LC_CTYPE","eng")后再把dataframe打印出来,如果一切正常就是不正常了
