### ISSUE TITLE
为什么rstudio下载不了REmap包啊？

### ISSUE THREAD

**Issue by liaoyuhua** [Lchiffon/REmap#18]
翻墙之后也下载不了。

**Comment by qinwf** [comment]
请使用

```
library(devtools)
install_github('lchiffon/REmap')
```


还有可以把你的安装代码和错误结果全部贴一些，信息越详细，越方便解决问题😄

**Comment by liaoyuhua** [comment]
> library("devtools")
Warning message:
程辑包‘devtools’是用R版本3.2.5 来建造的 
> install_github()
Error in lapply(repo, github_remote, username = username, ref = ref, subdir = subdir,  : 
  argument "repo" is missing, with no default
> install_github("lchiffon/REmap")
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Couldn't connect to server

**Comment by qinwf** [comment]
你试试下面的一些步骤，把结果发上来：

1、运行 

```
sessionInfo()
```

2、运行 

```
install.packages("devtools")
library(curl)
library(devtools)
install_github('lchiffon/REmap')
sessionInfo()
```

3、运行

```
library(curl)
curl_download("https://github.com","~/text.html",quiet = FALSE)
```

**Comment by qinwf** [comment]
还有

```
library(curl)
curl_download("https://api.github.com","~/text.html",quiet = FALSE)
```

**Comment by liaoyuhua** [comment]
> curl_download("https://api.github.com","~/text.html",quiet = FALSE)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0Error in curl_download("https://api.github.com", "~/text.html", quiet = FALSE) : 
  Couldn't connect to server

**Comment by Lchiffon** [comment]
看起来像是网络有问题, 试试这样安装:

下载下面这个链接:

https://github.com/Lchiffon/REmap/archive/master.zip

然后在Rstudio里面tools>InstallPackages> PackageArchive File(.zip .tar.gz) 
选择你下好的安装包, 然后安装

![image](https://cloud.githubusercontent.com/assets/7221728/25692287/e9a0ee62-30d3-11e7-863b-cd770ba78fa0.png)

**Comment by dsgwdl** [comment]
sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

curl_download("https://api.github.com","~/text.html",quiet = FALSE)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   493    0   493    0     0    585      0 --:--:-- --:--:-- --:--:--   596

在Rstudio里面tools>InstallPackages> PackageArchive File(.zip .tar.gz)
选择你下好的安装包, 然后安装。
安装之后Packages并未出现REmap。

**Comment by Lchiffon** [comment]
#20

**Comment by royi2014** [comment]
> install.packages("C:/Users/user/Desktop/REmap.zip", repos = NULL, type = "win.binary")
Warning in install.packages :
  cannot open compressed file 'REmap/DESCRIPTION', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection
>

**Comment by royi2014** [comment]
如果，我直接将下载包放在LIBRARY文件夹里，该放哪些文件

**Comment by Lchiffon** [comment]
总的说来， 装不上应该是网络问题，遇到了先试切换网络，比如用手机热点啊什么的

再装不上看下这个网页做手动安装 http://blog.csdn.net/han2538740718/article/details/52247798

再再装不上建议找朋友装好的包拷贝到自己的R/library文件夹里面
