### ISSUE TITLE
get_geo_position(city_vec)  errors

### ISSUE THREAD

**Issue by Jimjipeng** [Lchiffon/REmap#2]
Warning message:
In get_geo_position(city_vec) : 北京 not found.广州 not found.

**Comment by Lchiffon** [comment]
> city_vec1 = c("北京","上海","广州")
> get_geo_position (city_vec1)
>            lon       lat             city
> 12  116.413554 39.911013 北京
> 120 121.480237 31.236305 上海
> 21  113.270793 23.135308 广州

确保输入是UTF-8的编码

**Comment by Lchiffon** [comment]
参考 https://github.com/Lchiffon/REmap/issues/4

`Sys.setlocale("LC_CTYPE",
                  "English_United Kingdom.1252")`

**Comment by Jimjipeng** [comment]
Many Many Thanks！

**Comment by thwgithub** [comment]
你好，Dawei.
关于REmap有几个疑问请教你。_注：我已经加入了百度的ak_。我的sessionInfo（）如下：
R version 3.6.3 (2020-02-29)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1
Matrix products: default
Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 locale:
[1] LC_COLLATE=Chinese (Simplified)_People's Republic of China.936 
[2] LC_CTYPE=Chinese (Simplified)_People's Republic of China.936   
[3] LC_MONETARY=Chinese (Simplified)_People's Republic of China.936
[4] LC_NUMERIC=C                                                   
[5] LC_TIME=Chinese (Simplified)_People's Republic of China.936    
你们给出的源生例子运行没有问题：
#############
library(REmap)
set.seed(125)
out = remap(demoC,title = "REmap",subtitle = "theme:Dark")
plot(out)
summary(out)
################
**_但是，有如下问题：_**
（1） get_city_coord()不能获取经纬度，R中运行如下：
get_city_coord('shanghai')
[1] NA NA
get_city_coord('上海')
[1] NA NA

（2）get_geo_position （）不能获取英文地名的经纬度，R中运行如下：
city_vec = c("北京","上海")
get_geo_position (city_vec)
           lon       lat city
12  116.413554 39.911013 北京
120 121.480237 31.236305 上海
####
city_vec = c("北京","shanghai")
get_geo_position (city_vec)
          lon       lat city
12 116.413554 39.911013 北京
Warning message:
In get_geo_position(city_vec) : shanghai not found.
####

（3）remap问题。
remap运行你们的源生例子没有问题，但是运行如下例子就出问题
####
set.seed(125)
origin = rep("北京",10)
destination = c('上海','广州','大连','南宁','南昌', '拉萨','长春','包头','重庆','常州')
dat = data.frame(origin,destination)
out = remap(dat,title = "REmap",subtitle = "theme:Dark")
#Warning message:
#In get_geo_position(city_vec) :
#北京 not found.上海 not found.广州 not found.大连 not found.......
#####

我利用你给出的方法，Sys.setlocale("LC_CTYPE", "English_United Kingdom.1252")还是会出同样的问题。
设置之后：
第一个问题的运行情况：
get_city_coord('shanghai')
[1] NA NA
get_city_coord('上海' )
[1] NA NA

第二个问题运行情况：
 city_vec = c("北京","上海")
> get_geo_position (city_vec)
           lon       lat             city
12  116.413554 39.911013 <U+5317><U+4EAC>
120 121.480237 31.236305 <U+4E0A><U+6D77>

city_vec = c("北京","shanghai")
> get_geo_position (city_vec)
          lon       lat             city
12 116.413554 39.911013 <U+5317><U+4EAC>
Warning message:
In get_geo_position(city_vec) : shanghai not found.

第三个问题运行情况：
运行正常
不知道是什么原因，请指点，万分感谢。
