### ISSUE TITLE
Rstudio下载不了 REmap

### ISSUE THREAD

**Issue by ghsq123** [Lchiffon/REmap#20]
> library(devtools)
> install_github('lchiffon/REmap')
Installation failed: Problem with the SSL CA cert (path? access rights?)
怎么解决？？大神

**Comment by fanjingjinga** [comment]
我也是这个问题，贴上看到改默认浏览器为谷歌，改了也没用。

**Comment by Lchiffon** [comment]
这是一个devtools的问题, 与网络有关系, 你可以试一下其他github的包能不能装, 比如:
`devtools::install_github("yihui/xaringan")`

如果也装不了, 看下这个有没有帮助:
https://stackoverflow.com/questions/24793863/devtoolsinstall-github-ignore-ssl-cert-verification-failure
`set_config( config( ssl.verifypeer = 0L ) )`

**Comment by fanjingjinga** [comment]
谢谢你。
但还是出现问题了 这个包也安装不了，
用set_config( config( ssl.verifypeer = 0L ) )
提示Error in set_config(config(ssl.verifypeer = 0L)) : could not find function "set_config"。 

也尝试了在Rstudio里面tools>InstallPackages> PackageArchive File(.zip .tar.gz)选择自己下好的安装包, 然后安装。
要不出现这种问题，
> install.packages("D:/Users/asus/Desktop/REmap-master.zip", repos = NULL, type = "win.binary")
Warning in install.packages :
  unable to move temporary installation ‘D:\Users\asus\Desktop\R\R-3.4.0\library\file2d101eec159d\REmap-master’ to ‘D:\Users\asus\Desktop\R\R-3.4.0\library\REmap-master’
要不没问题时出现这样
> library("REmap")
Error in library("REmap") : 不存在叫‘REmap’这个名字的程辑包
也就是REmap还是没安装成功

**Comment by ghsq123** [comment]
不是直接运行set_config( config( ssl.verifypeer = 0L ) ) ，要运行这个set_config(use_proxy("123.123.123.123",8080))，不过不明白是什么意思

**Comment by Lchiffon** [comment]
@fanjingjinga 

第一个方法, 先`library(httr)`

对第二个方法, 把`REmap-master.zip`重命名成`REmap.zip`试试

因为没法重现问题, 只能这样debug了, :disappointed:

**Comment by ghsq123** [comment]
@Lchiffon 可以了，谢谢

**Comment by fanjingjinga** [comment]
@Lchiffon 
第一个方法又出错了
> library(httr)
> set_config( config( ssl.verifypeer = 0L ) )
> devtools::install_github("yihui/xaringan")
Installation failed: Unknown option: ssl.verifypeer

> library(httr)
> set_config(config(ssl.verifypeer = 0L))
> library(devtools)
> install_github('lchiffon/REmap')
Installation failed: Unknown option: ssl.verifypeer
set_config(use_proxy("123.123.123.123",8080))也是一样

第二个方法不能重命名
> install.packages("D:/Users/asus/Desktop/REmap.zip", repos = NULL, type = "win.binary")
Warning in install.packages :
  cannot open compressed file 'REmap/DESCRIPTION', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection
只能这样：
> install.packages("D:/Users/asus/Desktop/REmap-master.zip", repos = NULL, type = "win.binary")
> library(REmap)
Error in library(REmap) : 不存在叫‘REmap’这个名字的程辑包

为啥我还是不行[大哭]
但是之前我下载Tomcat时设置环境变量时 PATH的内容不小心被全部删除了..后来下载好了 看似没大影响。难道是这个原因？

**Comment by Lchiffon** [comment]
@fanjingjinga 
最后再给个办法, 再不行我也无能无力了
1. 解压zip文件
2. 点击REmap.Rproj
3. build&reload
![image](https://cloud.githubusercontent.com/assets/7221728/26041932/914eb896-3963-11e7-80df-68fc36b54530.png)

![image](https://cloud.githubusercontent.com/assets/7221728/26041957/c62785d4-3963-11e7-9f24-601fb4fa3353.png)

**Comment by fanjingjinga** [comment]
@Lchiffon 耽搁了些日子。谢谢你的帮助提点，方法很有效，我安装好了 谢谢你。

**Comment by dongqizhen15** [comment]
> @fanjingjinga
> 最后再给个办法, 再不行我也无能无力了
> 
> 1. 解压zip文件
> 2. 点击REmap.Rproj
> 3. build&reload
>    ![image](https://cloud.githubusercontent.com/assets/7221728/26041932/914eb896-3963-11e7-80df-68fc36b54530.png)
> 
> ![image](https://cloud.githubusercontent.com/assets/7221728/26041957/c62785d4-3963-11e7-9f24-601fb4fa3353.png)
GREAT

**Comment by Gladys0** [comment]
这个方法亲测有效，感谢大神，祝你生活愉快！
