### ISSUE TITLE
我想同时在一幅地图里面画两条线，这个该怎么办，好纠结

### ISSUE THREAD

**Issue by lsaihan** [Lchiffon/REmap#23]
我用的是remapB然后可以将自己的数据画成一条线，但是如果有好多组数据怎么办，比如我想绘制所有的上海的地铁的路线怎么办。

**Comment by Lchiffon** [comment]
http://langdawei.com/REmap/2015/06/remap4  你可以看下这个例子, 里面有绘制一号线的地图

多条线做legend的内容并没有做, 真做估计会在recharts里面实现, 毕竟REmap更多是偏向基本功能的

多说一句, 我做过上海地铁线路的绘制, 点太多了, 浏览器基本要崩

**Comment by lsaihan** [comment]
这样子说吧，我是做自然方向动物迁徙模型的点也是非常的多，然后我用remap绘制出来了一个动物的秋季路线之后没有办法继续在一个图里面呈现春季路线，如果可以把这个包做成可以在生态地理学上面有一番作为

**Comment by lsaihan** [comment]
补充一句，非常感谢你的贡献，我将能够获得的remap资料都读了试了一遍，非常谢谢

**Comment by Lchiffon** [comment]
这个你可以用不同的颜色做绘制， 你看下：

http://langdawei.com/REmap/2015/06/remap4

里面有一些代码你会用的上

```r
demoC$color = sample(c("red","blue"),10,replace = T)

remapB(title = "Remap:  百度迁徙模拟",
       color = "Blue",
       markLineData = demoC,
       markLineTheme = markLineControl(symbolSize = c(0,0),
                                       lineWidth = 10,
                                       effect = F,
                                       lineType = 'dashed'))
```
