### ISSUE TITLE
怎么能够获得百度地图的卫星地图

### ISSUE THREAD

**Issue by lsaihan** [Lchiffon/REmap#24]
很多时候，一个平面的公路图可以展示很多城市里面的信息，但是如果要运用到生态学上需要运用卫星地图这个该怎么调取卫星地图

**Comment by Lchiffon** [comment]
REmap是借用一个脚本把百度地图和echarts结合在一起, 换卫星地图目前并不能支持到

不过你可以试试leaflet: http://langdawei.com/leafletIntro/leafletSlides.html#12

**Comment by lsaihan** [comment]
谢谢lchiffon,想问您一下是否有兴趣把这个包深度开发

**Comment by lsaihan** [comment]
我看了一下leaflet的例子，还没有开始尝试，我深度学习一下后来很您交流谢谢
