### ISSUE TITLE
为什么函数readHTMLTable 抓取不了网页的表格

### ISSUE THREAD

**Issue by ghsq123** [Lchiffon/REmap#25]
请教各位大神，怎样抓取这个网站的表格数据，网站地址：http://www.beihaire.gov.cn:8080/xxgsweb/YfyjServlet?action=goYfyj&buildid=469615     

拜托了

**Comment by Lchiffon** [comment]
这个网页是动态加载的, 你查看下Network中做的请求, 有一个POST请求用来获取这个数据的...

**Comment by ghsq123** [comment]
不太明白，能说说要怎么样才能抓取么？

**Comment by Lchiffon** [comment]
你要找到名为 http://www.beihaire.gov.cn:8080/xxgsweb/YfyjServlet?action=goLiebiaoshitu 的一个POST请求, 然后按照请求的格式给这个网址POST数据: Form Data , 然后得到它的返回.

你可以用搜索引擎查查怎么用RCurl抓取网页

**Comment by ghsq123** [comment]
@Lchiffon  好的，我试试看

**Comment by ghsq123** [comment]
@Lchiffon 用这RCurl一样是抓取不了，能介绍下具体的做法吗
