### ISSUE TITLE
maptype能否设置为多个省份

### ISSUE THREAD

**Issue by huzhyi21** [Lchiffon/REmap#26]
在用REmap时，能否将maptype设置为多个省份。 

help文档里解释maptype：the type of the map. For example,'china', 'world' or other names of province in China.

尝试设置为多个省份报错 longer object length is not a multiple of shorter object length

是不是可以将REmap拓展到适用多个省份？

**Comment by Lchiffon** [comment]
这个不行， 受限于Echarts的接口
