### ISSUE TITLE
add Text

### ISSUE THREAD

**Issue by iamsuarez** [Lchiffon/REmap#28]
how to add text on the map with  using Remap Package

**Comment by iamsuarez** [comment]
怎么向地图上添加标签、或数据？基础作图、ggplot2作图都可以支持的。不知道，Remap包做的地图，是否可以添加标签。

**Comment by Lchiffon** [comment]
不可以， 这个受限于echarts， 如果你需要可以把内容生成为一个图片，再把图片当做点加进来， 点是可以选择图片路径的
