### ISSUE TITLE
REmap cannot been installed (solutions in #20 doesn't work either)

### ISSUE THREAD

**Issue by sammo3182** [Lchiffon/REmap#31]
Thank you for the great package. However, I tried multiple ways from the package `readme.md` and issue #20. None of them works.

When I tried
```r
library(devtools)
install_github('lchiffon/REmap')
```

R returns the following error:

```
Downloading GitHub repo lchiffon/REmap@master
from URL https://api.github.com/repos/lchiffon/REmap/zipball/master
Installing REmap

* installing *source* package 'REmap' ...
** R
** data
*** moving datasets to lazyload DB
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
ARGUMENT 'Hu_local\AppData\Local\Temp\Rtmpumn75g\Rin3fa8433c7b51' __ignored__

错误: 句法分析器1行里不能有多字节字符
停止执行
ERROR: loading failed
* removing 'D:/R/userLib/REmap'
Installation failed: Command failed (1)
```

When installing with an R system in English, I got slightly different messages but was still unsuccessful:

```
> install_github('lchiffon/REmap')
Downloading GitHub repo lchiffon/REmap@master
from URL https://api.github.com/repos/lchiffon/REmap/zipball/master
Installing REmap

* installing *source* package 'REmap' ...
** R
** data
*** moving datasets to lazyload DB
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
  converting help for package 'REmap'
    finding HTML links ... done
    REmapOutput                             html  
    get_city_coord                          html  
    get_geo_position                        html  
    get_theme                               html  
    knitrREmap                              html  
    mapNames                                html  
    markLineControl                         html  
    markPointControl                        html  
    plot.remap                              html  
    remap                                   html  
    remap.init                              html  
    remapB                                  html  
    remapC                                  html  
    remapH                                  html  
** building package indices
** testing if installed package can be loaded
ARGUMENT 'Hu_local\AppData\Local\Temp\RtmpEHI2Ty\Rin11444ce1e61' __ignored__

Error: object 'ÿþ' not found
Execution halted
ERROR: loading failed
* removing 'D:/R/userLib/REmap'
In R CMD INSTALL
Installation failed: Command failed (1)
```

When using `REmap.zip` file, I got the same message as royi2014 in #20: 

```
install.packages("C:/Users/user/Desktop/REmap.zip", repos = NULL, type = "win.binary")
Warning in install.packages :
cannot open compressed file 'REmap/DESCRIPTION', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection
```
When using `REmap-master.zip` file, the package seems installed but neither `library(REmap)` nor `library(REmap-master)` works.

I finally tried to build the package locally. I got the same message as I did through Github.

Here's my `sessionInfo`

```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices
[4] utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_3.4.2 tools_3.4.2   
[3] yaml_2.1.16   
```

**Comment by sammo3182** [comment]
This turns out not an issue of the package but the windows system. The solution is found here: https://github.com/hadley/devtools/issues/1693

**Comment by stewartli** [comment]
I have a same problem. I went through all steps you could found (remvove name space, rtools etc.). But nothing works so far. Can anyone help me out. Thank you. 
devtools::install_github("thomasp85/gganimate")
#> Downloading GitHub repo thomasp85/gganimate@master
#> from URL https://api.github.com/repos/thomasp85/gganimate/zipball/master
#> Installing gganimate
#> "C:/PROGRA~1/R/R-34~1.4/bin/x64/R" --no-site-file --no-environ --no-save  \
#>   --no-restore --quiet CMD INSTALL "C:/Users/Stewart  \
#>   Li/AppData/Local/Temp/RtmpAzlSwY/devtools43d45d264408/thomasp85-gganimate-8b3fc5b"  \
#>   --library="C:/Users/Stewart Li/Documents/R/win-library/3.4"  \
#>   --install-tests
#> 
#> Installation failed: Command failed (1)

**Comment by stewartli** [comment]
> devtools::install_github('thomasp85/gganimate')
Downloading GitHub repo thomasp85/gganimate@master
from URL https://api.github.com/repos/thomasp85/gganimate/zipball/master
Installing gganimate
"C:/PROGRA~1/R/R-34~1.4/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL "C:/Users/Stewart  \
  Li/AppData/Local/Temp/RtmpsJ4spS/devtools3ccc4100856/thomasp85-gganimate-8b3fc5b" --library="C:/Users/Stewart Li/Documents/R/win-library/3.4"  \
  --install-tests 

* installing *source* package 'gganimate' ...
** R
** tests
** preparing package for lazy loading
** help
*** installing help indices
  converting help for package 'gganimate'
    finding HTML links ... done
    anim_save                               html  
    animate                                 html  
    ease_aes                                html  
    enter_exit                              html  
    frame_vars                              html  
    gganimate-ggproto                       html  
    gganimate-package                       html  
    gif_file                                html  
    last_animation                          html  
    layer_type                              html  
    renderers                               html  
    save_animation                          html  
    shadow_mark                             html  
    shadow_null                             html  
    shadow_trail                            html  
    shadow_wake                             html  
    split_animation                         html  
    sprite_file                             html  
    transition_components                   html  
    transition_events                       html  
    transition_filter                       html  
    transition_layers                       html  
    transition_manual                       html  
    transition_null                         html  
    transition_reveal                       html  
    transition_states                       html  
    transition_time                         html  
    tween_before_stat                       html  
    video_file                              html  
    view_follow                             html  
    view_static                             html  
    view_step                               html  
    view_zoom                               html  
*** copying figures
** building package indices
** testing if installed package can be loaded
*** arch - i386
Fatal error: cannot open file 'C:\Users\Stewart': No such file or directory

*** arch - x64
Fatal error: cannot open file 'C:\Users\Stewart': No such file or directory

ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Users/Stewart Li/Documents/R/win-library/3.4/gganimate'
In R CMD INSTALL
Installation failed: Command failed (1)
