### ISSUE TITLE
remap() error 

### ISSUE THREAD

**Issue by mxfreedom** [Lchiffon/REmap#4]
library(REmap)
city_vec = c("北京","上海","广州","大连","南宁","南昌","拉萨","长春","包头","重庆","常州")
get_geo_position (city_vec)
      lon       lat                     city
1   119.980142 31.816791 常州
12  116.413554 39.911013 北京
set.seed(125)
origin = rep("北京",10)
destination = c('上海','广州','大连','南宁','南昌', '拉萨','长春','包头','重庆','常州')
dat = data.frame(origin,destination)
 out = remap(dat,title = "REmap",subtitle = "theme:Dark")
Warning message:
In get_geo_position(city_vec) :
  北京 not found.上海 not found.广州 not found.南宁 not found.南昌 not found.拉萨 not found.长春 not found.包头 not found.重庆 not found.常州 not found.

请问 get_geo_position (city_vec) 可以运行成功，为什么 remap() 结果却是 not found 呢?

**Comment by Lchiffon** [comment]
我这边是没有问题的,试一下以下代码有没有报错..另外贴下你的`sessionInfo()`吧

```
mapdata = dat 
if(!is.character(mapdata[1,1])){
  mapdata[,1] = as.character(mapdata[,1])
  mapdata[,2] = as.character(mapdata[,2])
  }
  city_vec = unique(c(mapdata[,1],mapdata[,2]))

  Geo_data = get_geo_position(city_vec)
```

**Comment by mxfreedom** [comment]
Thanks so much! 代码没有报错。昨天运行成功过，还做了我自己采样点的remap。但今天却运行不了，尝试过重新安装REmap package依然不可以。sessionInfo()如下：

> sessionInfo()
> R version 3.2.5 (2016-04-14)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Chinese (Simplified)_People's Republic of China.936 
[2] LC_CTYPE=Chinese (Simplified)_People's Republic of China.936  
[3] LC_MONETARY=Chinese (Simplified)_People's Republic of China.936
[4] LC_NUMERIC=C  
[5] LC_TIME=Chinese (Simplified)_People's Republic of China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] REmap_0.3.2

loaded via a namespace (and not attached):
[1] rjson_0.2.15    htmltools_0.3.5 Rcpp_0.12.5     digest_0.6.9  
[5] XML_3.98-1.4

**Comment by Lchiffon** [comment]
试试

```
Sys.setlocale("LC_CTYPE",
                  "English_United Kingdom.1252")
```

以后`get_geo_position`能用不>.<

**Comment by mxfreedom** [comment]
Sys.setlocale("LC_CTYPE",
                  "English_United Kingdom.1252")
之后 可以了！谢谢！！！
