### ISSUE TITLE
remapB生成html一片空白

### ISSUE THREAD

**Issue by SuperFrank08** [Lchiffon/REmap#43]
remapB生成html时一片空白，没有报错，之前使用也没有问题

**Comment by SuperFrank08** [comment]
remapB(center = c(104.114129,37.550339),
       zoom = 5,
       color = "Bright",
       title = "",
       subtitle = "",
       markLineData = NA,
       markPointData = NA,
       markLineTheme = markLineControl(),
       markPointTheme = markPointControl(),
       geoData = NA)

**Comment by Lchiffon** [comment]
echarts官网链接调整，已修复, 谢谢
