### ISSUE TITLE
Shiny上用不了了

### ISSUE THREAD

**Issue by QingXiangBaiLian** [Lchiffon/REmap#7]
郎老师您好，我想问下您这个REmap最近好像在shiny上用不了了，试了iOS与Windows都出现以下错误，

> example("REmapOutput")
> Error:XML content does not seem to be XML: '{
>     "status":0,
>     "message":"ok",
>     "results":[
>         {
>             "name":"常州市",
>             "location":{
>                 "lat":31.816791,
>                 "lng":119.980142
>             },
>             "uid":"d154daec3431f54d057ce8f0"
>         }
>     ]
> }'
> ![Uploading 屏幕快照 2016-09-04 10.55.25.png…]()

**Comment by lixinyao** [comment]
@QingXiangBaiLian 我也是这个问题～

**Comment by lichangzai** [comment]
我也是同样的问题，在shiny的shinydashboard中使用REmapOutput("remap")时，整个shiny里的其它功能都不能用，出现半个屏的白板； 而且使用代码中的demo时，地图也不显示，谷歌的浏览器也不行。
希望您能尽快解决，着急用啊，谢谢！

**Comment by lixinyao** [comment]
@Lchiffon 我的问题解决了，可以在shiny上使用REmap绘制迁徙图了。但是`REmapOutput`和DT包的`dataTableOutput`一起使用时，表格不会显示；如果不使用REmap，**将`REmapOutput`替换为`plotOutput`，表格则会显示**。是REmap和DT不兼容吗？谢谢啦郎老师 :grin:

**Comment by maliang1202** [comment]
请问问题解决了吗？

**Comment by Lchiffon** [comment]
前面那个问题我应该解决了， 后面怎么歪到另一个问题了....
```r
example("REmapOutput")
```
这段没问题了吧

@lixinyao 给段代码？

**Comment by Lchiffon** [comment]
这个issue应该是解决掉了， 关于DT的我们移步到
#29 讨论
