### ISSUE TITLE
如何在小区/街道范围内绘制热力图？

### ISSUE THREAD

**Issue by zheguzai100** [Lchiffon/REmap#8]
想实现的效果 code化 就是
remapH(data,center=,zoom=,theme,blursize,....)
即 用center=坐标值,zoom=放大系数 来限定显示区域，而不是使用大而全的maptype=c('china','world','name of province in China')

**Comment by Lchiffon** [comment]
这个功能REmap应该不会添加， 可以看下leaflet和leaflet.extra的组合

https://github.com/bhaskarvk/leaflet.extras
